#management:
 # endpoints:
    #web:
      #exposure:
        #include: hystrix.stream, info, health
        
# Discovery Server Access
#eureka:
  #client:
    #serviceUrl:
     # defaultZone: http://localhost:8761/eureka

# HTTP Server
server:
  port: 3335
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_matriculas?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    generate-ddl: true
    
